version: '3.7'
services:
  tf2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
    ports:
      - '8888:8888'
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    stdin_open: true
    tty: true